chore(analytics): DATA-11047 Add line item index and event_id fields for bodl events
bigcommerce/stencil-utils pull request #206
Opened 2023-05-22 12:16 UTC by bc-rmalyavc

## What [DATA-11047](https://bigcommercecloud.atlassian.net/browse/DATA-11047)
- Add `event_id` field for `BODL` events
- Change `product_id` field type to string 

## Why
As per the [requirements](https://docs.google.com/document/d/13qlYa9gtuVcjs2iBZ-jWP74W1GPRQw9J496t7QYbbJg/edit#heading=h.7ukms7o1890s) we should have both fields for all events

[DATA-11047]: https://bigcommercecloud.atlassian.net/browse/DATA-11047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-05-22 12:23 UTC, solofeed approved these changes

2023-05-22 16:22 UTC, jairo-bc requested changes
@bc-rmalyavc couple notes on the release:
- I believe it's a fix PR type, rather than chore type. chore - doesn't update app code.
- since it's a fix, a minor version bump should be done 
- please bump version in a separate PR. 

Code changes looks good to me

2023-05-23 10:37 UTC, bc-rmalyavc commented
@jairo-bc,
Thanks for the review. Updated the PR type. Also please see the [bump PR](https://github.com/bigcommerce/stencil-utils/pull/207).

2023-05-24 11:03 UTC, jairo-bc approved these changes

2023-06-07 10:49 UTC, merged